#!/usr/bin/env node

var bs = require("browser-sync").create();

bs.init({
  proxy: 'https://xeven.icu',
  open: false,
  files: [
    '*.{html,js,css}'
  ],
  ghostMode: {
    clicks: false,
    forms: false,
    scroll: false
  },
  logConnections: true,
  logFileChanges: true,
});
